# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a25cb6e458e6f43a772255b8053c4385133b1c90bcbaa14412895211bce390963de96d993a02a43f8b76d7db9acf91989a38ab5d9f6af94f6594fe3465f75af

test:
  secret_key_base: 13a7f524afc797ecc9b9ff0bfd77d927c7bff79e97dc879480f2944cb54e62eb4a13ae7f469e5d03e7e75da024d23977669f1348137cd4ebead2078edd318db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
