# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f4f6b31ea7a7bacba65908979e2de512ac9142bf6b89c84651b2bb025e362c452f4c59e06df32a6f332e23d59689bd63a2b9b8c677b6ca30fa216b46f9f2621

test:
  secret_key_base: b348f7389aae312f7436d257fd738b15f27241adc87519b7354d62a61061763ad3886db257d589af7966722a64c5a32d17b402fba12c40374a462592fb9039f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
